config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get '/about', to: 'static#about'

  devise_for :users,
              path: '',
              path_names:{
                sign_in: 'login',
                sign_out: 'logout',
                sign_up: 'register'
              }

  resources :posts



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_and_belongs_to_many :tags
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :posts
  has_many :users, through: :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments, through: :posts
  has_many :tags, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
#for the whole app, if put before_action: authenticate_user here, cant view any page. need to be logged in. shift the before_action: authenticate_user to specific pages which you dont want public pages
before_action :configure_permitted_parameters, if: :devise_controller?
# before_action :authenticate_user!
protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :occupation])
end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
# before_action :authenticate_user!, only: [:new, :edit]
#use except
  def index

    news_url = 'https://newsapi.org/v1/articles?source=engadget&sortBy=top&apiKey=1eff6268512d43ff87125794dccec730'

    response = HTTParty.get(news_url)

    # render json: response

    @news = response

    # render json: current_user.posts

    @all_posts = current_user.posts
    @new_post = current_user.posts.new

    # render json: current_user.name
  end

  def show
    @post = Post.find(params[:id])
    # render html: 'show one post'
  end

  def new
    render html: 'new posts'
  end

  def edit
      @update_post= Post.find(params[:id])
    # render json: @update_post
  end

  def update
    # updated_post= Post.find(params[:id])
    # updated_post.title = params[:post][:title]
    # updated_post.content = params[:post][:content]
    # updated_post.save

# or
    Post.find(params[:id]).update(post_params)

    redirect_to posts_path
  end

  def create
    # creating_post = params.require(:post).permit(:title, :content, :user_id)


    # or
    # creating_post = current_user.post.build
    # creating_post.title = params[:post][:title]


    # render json: @creating_post

    Post.create(post_params)

    redirect_to posts_path
  end

  def destroy
    Post.destroy(params[:id])
    # OR
    # deleted_post = Post.find(params[:id])
    # deletd_post.destroy

    redirect_to posts_path
  end

private

def post_params

  params.require(:post).permit(:title, :content, :user_id)

end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
before_action :authenticate_user!, only: [:about]

  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggiesPsql</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post <%= @update_post.id %></h2>

<%= form_for @update_post  do |f| %>
<%= f.label :title %>
  <%= f.text_field :title %>
  <br><br>
  <%= f.label :content %>
    <%= f.text_area :content %>

      <%= f.submit %>


<% end %>

app/views/posts/index.html.erb
<h1>All posts by <%= current_user.name %></h1>

<h2>News from API</h2>

<ul>
  <% @news["articles"].each do |article| %>

  <li>
    <!-- <h2><%= article %></h2> -->
<h3><%= article['title'] %></h3>
<p><%= article['description'] %></p>
<img src= <%= article['urlToImage'] %> alt=<%= article['title'] %>>
<h5><%= article['publishedAt'] %></h5>
<a href= <%= article['url']%>> Read more.. </a>


  </li>

  <% end %>

</ul>



<ul>
  <%@all_posts.each_with_index do |post,index| %>
  <% if post.id %>
  <li>
    <!-- <%= index %> -->
<h4><%= post.title %></h4>
<p><%= post.content %></p>
<%= link_to "View", post_path(post) %>
<%= link_to "Delete", post_path(post), method: :delete %>
<%= link_to "Update", edit_post_path(post) %>
  </li>
  <% end %>
  <% end %>
</ul>

<%= form_for @new_post do |f| %>
<%= f.label :title %>
  <%= f.text_field :title %>
<br><br>
  <%= f.label :content %>
    <%= f.text_area :content %>
<br><br>

<%= f.hidden_field :user_id %>
    <%= f.submit %>
<% end %>

<%= @new_post.inspect %>

<!-- <%= @all_posts.inspect %> -->

app/views/posts/show.html.erb
<!-- <%= @post.inspect %> -->

<h1>Author: <%= @post.user.name %></h1>
<h2><%= @post.title %></h2>

<p><%= @post.content %></p>

<h4>Created at:</h4>
<h4><%= @post.created_at %></h4>